In [387]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [388]:
import numpy as np 

a = np.ndarray((2, 3))
a

array([[2. , 2.8, 3.6],
       [4.4, 5.2, 6. ]])

In [389]:
np.ndrray?

Object `np.ndrray` not found.


In [390]:
import numpy as np 

a = np.ndarray(shape=(2,2), dtype = int)
a

array([[            0, 2714526003936],
       [2714526005296, 2714526004816]])

In [391]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)

(2, 2)
2
4
8
int64
32


In [392]:
a.data

In [393]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [394]:
import numpy as np 

a = np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [395]:
type(a)

numpy.ndarray

In [396]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [397]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [398]:
a.data

In [399]:
np.array(1,2,3) #오류

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np 

unicode_array = np.array(['가나다', '라마바', '사아자'],dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'],dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'],dtype='<U64')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마', '라마바', '사아자'], dtype='<U64')

In [ ]:
lang = np.array(['파이썬','자바','씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1,2.5,3))
b

array([1. , 2.5, 3. ])

In [ ]:
import numpy as np 
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np 
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0,6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
#이러한 애매한 상황이 발생하지 않도록 
#step: 0으로 반복횟수만 원래의 계산으로 수행해 10개의 0이 생성
np.arange(0,5,0.5,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(-3,3,0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
b= np.array([1,2,3,4,5,6]).reshpe(3,2)
b

AttributeError: 'numpy.ndarray' object has no attribute 'reshpe'

In [ ]:
np.reshape(b, (2, -1))
np.reshape(b, (5, -1))
np.reshape(b, (6, -1))


ValueError: cannot reshape array of size 3 into shape (2,newaxis)

In [ ]:
np.linspace(2.0,3.0) #(2.0, 3.0,50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [ ]:
print((3-2) / (50-1))

0.02040816326530612


In [ ]:
np.linspace(2.0,3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [ ]:
print((3-2) /50)

0.02


In [ ]:
np.limnspace(2.0,3.0, num=5,retstep=True)

AttributeError: module 'numpy' has no attribute 'limnspace'

In [ ]:
np.linspace(2.0,3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [ ]:
#0.4가 나오지 않아야 하나 부동소우의 문제로
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [ ]:
np.arange(1,4,1) / 10.0

array([0.1, 0.2, 0.3])

In [ ]:
np.linespace(0.1,0.4,3, endpoint=False)

AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
np.linespace(0.1,0.4,4)

AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
import numpy as np 
a = np.zero(5)
a

AttributeError: module 'numpy' has no attribute 'zero'

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [ ]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [ ]:
b.shape

(3, 4)

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.eye(3,4,1)
a


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
b = np.eye(3,4,-1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [ ]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([2,3],(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [ ]:
np.full((3,4), range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4,3], fill_value_np(4).reshape(4,1))

NameError: name 'fill_value_np' is not defined

In [ ]:
np.empty(3)

array([0.1, 0.2, 0.3])

In [ ]:
np.empty(2,2)

TypeError: Cannot interpret '2' as a data type

In [ ]:
np.empty([2,3],dtype=int)

array([[4611686018427387904, 4613487458278336102, 4615288898129284300],
       [4616639978017495449, 4617540697942969548, 4618441417868443647]])

In [ ]:
np.empty((3,2,3),int)

array([[[           16, 2714491899216, 2714461705536],
        [2714461705344, 2714452144016, 2714461705952]],

       [[2714461706304, 2714461704704, 2714461704736],
        [2714461706016, 2714452142480, 2714461706048]],

       [[2714534886784,             0,             0],
        [            0,             0,             0]]])

In [ ]:
import numpy as np
a = np.arange(8).reshpe(2,4)
a

AttributeError: 'numpy.ndarray' object has no attribute 'reshpe'

In [ ]:
np.zero_like(a)

In [ ]:
np.ones_like(a)

array([1, 1, 1])

In [ ]:
np.full_like(a, range(6))

ValueError: could not broadcast input array from shape (6,) into shape (3,)

In [ ]:
import numpy as np 
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
print( 1 +2)
print( 1 -2)
print( 1 *2)
print( 1 / 2)

3
-1
2
0.5


In [ ]:
b = np.full_like(a, [1,2,3])
b

array([1, 2, 3])

In [ ]:
print( a +b)
print( a - b)
print( a *b )
print( a / b)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(0.5,4,1)
b

array([0.5, 1.5, 2.5, 3.5])

In [ ]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
b += a 
b

ValueError: non-broadcastable output operand with shape (2,1) doesn't match the broadcast shape (2,3)

In [ ]:
a = np.full((2,3), [1,2,3,])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
b =np.full((3,2), [2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [ ]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [ ]:
a.dot(b)

ValueError: shapes (3,4) and (2,1) not aligned: 4 (dim 1) != 2 (dim 0)

In [ ]:
b.dot(b)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
b.dot(a)

ValueError: shapes (2,1) and (3,4) not aligned: 1 (dim 1) != 3 (dim 0)

In [ ]:
import numpy as np 
print(np.matmul(a, b))
print(np.matmul(b,a))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [ ]:
a = np.array([[10, 20], [2,8], [1,2]])
a

In [ ]:
a.sum()

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [ ]:
import numpy as np 
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

In [ ]:
a = np.array([[3,5,8],[1,2,3]])
a

In [ ]:
#일차원으로 펼쳐서 계산
a.cumsum()

In [ ]:
a.cumsum(axis=0) #행을 따라 세로로 합산
#[3,5,8]
#[1,2,3]
#>> [3,5,8]
#>> [3+1, 5+2, 8+3]

In [ ]:
a.cumsum(axis=1) #열을 따라 가로로 합산

In [ ]:
import numpy as np 
a = np.array([1,4,9])
np.sqrt(a)


array([1., 2., 3.])

In [ ]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [ ]:
import numpy as np 
a = np.array([1,4,9])
a

In [ ]:
b = np.full_like(a,2)
b

In [ ]:
np.add(a,b)

In [ ]:
np.divide(a,b)

In [ ]:
np.power(a,b)

In [ ]:
import numpy as np 
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[]
[3 2 1]


In [ ]:
a[::-1]

array([3, 2, 1])

In [ ]:
a[::-2]

array([3, 1])

In [ ]:
a[2:5] = -100 
a

array([   1,    2, -100])

In [ ]:
a[2:5] = [-5,-5,-5]
a

In [ ]:
a[2:5] = [-5,-5]
a

In [ ]:
a[2:5] = -10
a

array([  1,   2, -10])

In [ ]:
b = np.array([5]*10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [ ]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [ ]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
a[-2, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
a[-2, ]

np.int64(2)

In [ ]:
a[2:4]

array([3])

In [ ]:
a[1:5:2]

array([2])

In [ ]:
a[:, 1]

In [ ]:
a[:, 1:6]

In [ ]:
a[:, ::2]

In [ ]:
a[::2]

array([1, 3])

In [ ]:
a[2,4]

In [ ]:
a[2][4]

In [ ]:
a[:]

In [ ]:
a[::-1, ::-1]


In [ ]:
#마지막 행과 열을 제외한 배열 반환
a[:-1, :-1]


In [ ]:
a = np.arange(24).reshape(2,3,4)
a

In [ ]:
a[1]

In [ ]:
a[:, 1]

In [ ]:
a[:,1 ,1]

In [ ]:
a[:,:,1]


In [ ]:
a[...,1]

In [ ]:
a[1, ..., 1]

In [ ]:
a

In [ ]:
a[:, :,2:]

In [ ]:

a[:,:,3:]

In [ ]:
a[:,:,3]

In [ ]:
a = np.arange910.reshape(2,3,2)
a

In [ ]:
b = a.raval()
b

In [ ]:
b[0] = 100
b

In [ ]:
b[0] =100
b

In [ ]:
a

In [ ]:
a= np.arange(1,7).reshape(2,3)
a

In [ ]:
np.transpose(a)

In [ ]:
a.trandpose()

In [ ]:
a.T

In [ ]:
np.transpose(a,(0.1))



In [ ]:
np.transpose(a, (1,0))

In [ ]:
b = np.arnage(1,13).reshape(3,2,2)
b

In [ ]:
b.T

In [ ]:
np.transpose(b, (0,1,2))

In [ ]:
np.transpose(b, (2,1,0))

In [ ]:
np.transpose(b, (0,2,1))

In [ ]:
c = np.arange(1,13).reshape(2,2,3)
c

In [ ]:
c.transpose(b,)

In [ ]:
c.transpose((1,2,0))

In [ ]:
c = np.arange(1,13).reshape(2,2,3)
c

In [ ]:
np.transpose(c,(1,2,0))

In [ ]:
c.transpose(c)